[theme]
primaryColor = "#DC143C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#221F1F"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false